### ISSUE TITLE
Adding tags would help for production users

### ISSUE THREAD

**Issue by holms** [frol/docker-alpine-ruby#2]
Hi :)

Without tags it's a bit difficult to stay on same version in production, maybe you can add tags please :)? Currently this would be a current ruby version which is used.

Thanks :)

**Comment by frol** [comment]
This Docker image follows Alpine repository, so it is beyond my control to pin the version. However, I suggest you use official `ruby:alpine`, or `ruby:2.3.1-alpine`, or any other tag which makes sense in your case of the [official Docker Hub ruby image](https://hub.docker.com/_/ruby/). Unfortunately, their image is weirdly fat - 125MB vs 20MB.

**Comment by holms** [comment]
if I were you I’d add ruby version when installing through apk command, then you can do tags :)
Oh well will do this for myself then.

**Comment by frol** [comment]
This will only ensure that newer version of Ruby will break Docker image build. Alpine Linux repos don't include previous versions of packages. Thus, once new Ruby version is released, I won't be able to create an image with previous Ruby release and new system updates/fixes.

**Comment by holms** [comment]
There are plenty of packages with multiple versions in there.. for now there’s just one version for ruby.
http://pkgs.alpinelinux.org/packages?name=ruby&branch=v3.4&repo=&arch=&maintainer=

Just specifying that version when installing won’t brake anything. once new version will come out, old one won’t be deleted :)

**Comment by frol** [comment]
> once new version will come out, old one won’t be deleted :)

May I ask you why do you think so? I'm building Alpine-based images and contribute into Alpine for over 1.5 years and from my experience old packages are always removed once new package with the same name is built.
